package fullstack.homeWork.functionalTest;

// Generated by Selenium IDE
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import io.github.bonigarcia.wdm.WebDriverManager;

import org.openqa.selenium.Dimension;
import org.openqa.selenium.Keys;
import org.openqa.selenium.JavascriptExecutor;
import java.util.HashMap;
import java.util.Map;

import java.time.Duration;

public class FunctionalTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  
  @BeforeEach
  public void setUp() {
    WebDriverManager.firefoxdriver().setup();
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterEach
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void functionalTest() {
    driver.get("http://localhost:8080/");
    driver.manage().window().setSize(new Dimension(1854, 1048));
    driver.findElement(By.linkText("Math Dept. Snack Bar - University of Aveiro")).click();
    driver.findElement(By.name("studentName")).click();
    driver.findElement(By.name("studentName")).sendKeys("goncalo");
    driver.findElement(By.cssSelector(".day-container:nth-child(1) button")).click();
    driver.findElement(By.linkText("Back to Restaurant")).click();
    driver.findElement(By.cssSelector(".day-container:nth-child(2) input")).click();
    driver.findElement(By.cssSelector(".day-container:nth-child(2) input")).sendKeys("goncalo");
    driver.findElement(By.cssSelector(".day-container:nth-child(2) form")).click();
    driver.findElement(By.linkText("Back to Restaurant")).click();
    driver.findElement(By.cssSelector(".day-container:nth-child(3) input")).click();
    driver.findElement(By.cssSelector(".day-container:nth-child(3) input")).sendKeys("goncalo");
    driver.findElement(By.cssSelector(".day-container:nth-child(3) button")).click();
    driver.findElement(By.linkText("Back to Restaurant")).click();
    driver.findElement(By.cssSelector(".day-container:nth-child(6) input")).click();
    driver.findElement(By.cssSelector(".day-container:nth-child(6) input")).sendKeys("joao");
    driver.findElement(By.cssSelector(".day-container:nth-child(6) button")).click();
    driver.findElement(By.linkText("Back to Restaurant")).click();
    driver.findElement(By.linkText("Back to Home")).click();
    driver.findElement(By.linkText("Check Your Reservations")).click();
    driver.findElement(By.name("studentName")).click();
    driver.findElement(By.name("studentName")).sendKeys("goncalo");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.cssSelector("li:nth-child(1) button")).click();
    driver.findElement(By.name("studentName")).click();
    driver.findElement(By.linkText("Back to Home")).click();
    driver.findElement(By.linkText("Worker Check-In")).click();
    driver.findElement(By.cssSelector(".reservation-card:nth-child(1) button")).click();
    driver.findElement(By.cssSelector(".reservation-card:nth-child(2) > form span")).click();
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.linkText("Back to Home")).click();
    driver.findElement(By.linkText("Check Your Reservations")).click();
    driver.findElement(By.name("studentName")).click();
    driver.findElement(By.name("studentName")).sendKeys("goncalo");
    driver.findElement(By.name("studentName")).sendKeys(Keys.UP);
    driver.findElement(By.name("studentName")).sendKeys(Keys.DOWN);
    driver.findElement(By.name("studentName")).sendKeys(Keys.DOWN);
    driver.findElement(By.name("studentName")).sendKeys("goncalo");
    driver.findElement(By.cssSelector("button")).click();
    driver.findElement(By.linkText("Back to Home")).click();
  }
}
